# Difficulty Scaling Focal Loss Ablation Study
# All experiments use EXACT same config except difficulty scaling

study_name: "difficulty_scaling_ablation"
wandb_project: "Difficulty_analysis_IEMO_v3.0"

# Template config that achieved 70.8% - ALL experiments inherit this
template_config: &template
  learning_rate: 9e-5
  weight_decay: 5e-6
  use_curriculum_learning: true
  use_speaker_disentanglement: true
  difficulty_method: "euclidean_distance"
  focal_loss: true
  focal_alpha: 0.25
  focal_gamma: 1.0
  label_smoothing: 0.1
  num_epochs: 80
  batch_size: 32
  class_weights:
    neutral: 0.8
    happy: 3.5
    sad: 1.8
    anger: 1.6
  classifier_config:
    architecture: "simple"
    hidden_dim: 1536
    pooling: "attention"
    layer_norm: true
    dropout: 0.4
    input_dropout: 0.2
  curriculum_epochs: 35
  curriculum_pacing: "exponential"
  use_difficulty_scaling: true  # New parameter for ablation
  training_direction: "IEMOCAP_to_MSP"
  # training_direction: "MSP_to_IEMOCAP"  # "IEMOCAP_to_MSP" or "MSP_to_IEMOCAP"

experiments:

  # ========== DIFFICULTY SCALING ABLATION ==========
  
  - <<: *template
    id: "diff_scaling_on_curriculum_on"
    name: "Difficulty Scaling + Curriculum + SD"
    description: "Full setup: difficulty-scaled focal loss + curriculum learning"
    category: "full_method"
    use_difficulty_scaling: true
    use_curriculum_learning: true
    use_speaker_disentanglement: true

  # - <<: *template
  #   id: "diff_scaling_off_curriculum_on"
  #   name: "Standard Focal + Curriculum"
  #   description: "Standard focal loss + curriculum learning (no difficulty scaling)"
  #   category: "ablation"
  #   use_difficulty_scaling: false
  #   use_curriculum_learning: true
  #   use_speaker_disentanglement: true

  - <<: *template
    id: "diff_scaling_on_curriculum_off"
    name: "Difficulty Scaling Only"
    description: "Difficulty-scaled focal loss without curriculum learning"
    category: "ablation"
    use_difficulty_scaling: true
    use_curriculum_learning: false
    use_speaker_disentanglement: true

  # - <<: *template
  #   id: "diff_scaling_off_curriculum_off"
  #   name: "Standard Focal Only"
  #   description: "Standard focal loss without curriculum learning (baseline)"
  #   category: "baseline"
  #   use_difficulty_scaling: false
  #   use_curriculum_learning: false
  #   use_speaker_disentanglement: true

  # # ========== ADDITIONAL CONTROLS ==========

  - <<: *template
    id: "Difficulty Scaling + Curriculum"
    name: "Difficulty Scaling + Curriculum"
    description: "Full method but without speaker disentanglement"
    category: "control"
    use_difficulty_scaling: true
    use_curriculum_learning: true
    use_speaker_disentanglement: false 

  - <<: *template
    id: "Baseline"
    name: "Baseline"
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    use_difficulty_scaling: false
    use_curriculum_learning: false
    use_speaker_disentanglement: false 

  # - <<: *template
  #   id: "35_epochs_exponential_quadratic"
  #   name: "35_epochs_exponential_quadratic"
  #   curriculum_epochs: 35
  #   description: "Exact replica of label_smoothing config that achieved 70.8%"
  #   category: "baseline"
  #   difficulty_method : "baseline_quadratic"
    



analysis:
  primary_metric: "iemocap_wa"
  baseline_wa: 0.708
  target_wa: 0.72
  
  research_questions:
    - "Does difficulty-scaled focal loss improve performance over standard focal loss?"
    - "How much does curriculum learning contribute vs difficulty scaling?"
    - "Do curriculum learning and difficulty scaling work synergistically?"
    - "Is the new difficulty rescaling (percentile + sigmoid) effective?"

estimated_runtime:
  total_experiments: 5
  minutes_per_experiment: 240
  total_hours: 20