# Curriculum Pacing Ablation Study - FIXED VERSION
# All experiments use EXACT same config except curriculum pacing

study_name: "Current_Method_Ablation"
wandb_project: "Current_Method_Ablation"

# Template config that achieved 70.8% - ALL experiments inherit this
template_config: &template
  learning_rate: 9e-5
  weight_decay: 5e-6
  use_curriculum_learning: true
  use_speaker_disentanglement: true
  difficulty_method: "pearson_correlation"
  lr_scheduler: "cosine"
  focal_loss: true
  focal_alpha: 0.25
  focal_gamma: 2.0
  label_smoothing: 0.1
  num_epochs: 80
  batch_size: 16
  class_weights:
    neutral: 0.8
    happy: 3.5
    sad: 1.8
    anger: 1.6
  classifier_config:
    architecture: "simple"
    hidden_dim: 1536
    pooling: "attention"
    layer_norm: true
    dropout: 0.4
    input_dropout: 0.2

experiments:
  # ========================================
  # BASELINE
  # ========================================
  
  - <<: *template
    id: "Speaker+Curriculum"
    name: "Speaker + Curriculum"
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"

  - <<: *template
    id: "Speaker_Only"
    name: "Speaker_Only"
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    use_curriculum_learning: false

  - <<: *template
    id: "Curriculum_Only"
    name: "Curriculum_Only"
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    use_speaker_disentanglement : false

  - <<: *template
    id: "Baseline"
    name: "Baseline "
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    use_speaker_disentanglement : false
    use_curriculum_learning : false

  - <<: *template
    id: "Preset_Curriculum"
    name: "Preset_Curriculum "
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    difficulty_method : "preset"
    use_speaker_disentanglement : false

  - <<: *template
    id: "Preset_Curriculum+Speaker"
    name: "Preset_Curriculum+Speaker"
    curriculum_epochs: 30
    description: "Exact replica of label_smoothing config that achieved 70.8%"
    category: "baseline"
    difficulty_method : "preset"




analysis:
  primary_metric: "iemocap_wa"
  baseline_wa: 0.708
  target_wa: 0.72
  
  research_questions:
    - "What is the optimal curriculum pacing for this dataset?"
    - "Does slower or faster curriculum progression work better?"
    - "Can non-linear pacing strategies outperform linear?"

estimated_runtime:
  total_experiments: 15
  minutes_per_experiment: 240
  total_hours: 60