# Extended Top Performers Ablation Study
# Testing top 3 performers with speaker disentanglement and class weighting variations
# Goal: Push beyond 68.58% WA towards 70%+ target

study_name: "top_performers_extended_ablation"
wandb_project: "emotion2vec_top_performers_extended_V2"

# Base configuration for all experiments
base_config:
  # Core training parameters
  num_epochs: 50
  batch_size: 20
  lr_scheduler: "cosine"
  
  # Base setup - will be overridden per experiment
  use_curriculum_learning: false
  use_speaker_disentanglement: false
  difficulty_method: "original"
  curriculum_epochs: 20
  
  # FULL EVALUATION - ALL SESSIONS (no single_test_session parameter)

# Experiment definitions
experiments:
  # ========================================
  # BASELINE FOR COMPARISON
  # ========================================
  
  - id: "baseline_reference"
    name: "Baseline Reference"
    learning_rate: 3e-4
    weight_decay: 1e-4
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 512
      pooling: "max_mean"
      layer_norm: true
      dropout: 0.2
    description: "Reference baseline with standard class weights"
    category: "baseline"

  # ========================================
  # TOP PERFORMER #1: ULTRA PEARSON MAXIMUM (68.58% WA)
  # Testing speaker disentanglement and class weight variations
  # ========================================
  
  - id: "ultra_pearson_original"
    name: "ULTRA: Pearson Original"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 2.0
      sad: 1.3
      anger: 1.3
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "Original ULTRA Pearson (68.58% WA baseline)"
    category: "top_performer"

  - id: "ultra_pearson_speaker"
    name: "ULTRA: Pearson + Speaker"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 2.0
      sad: 1.3
      anger: 1.3
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA Pearson + speaker disentanglement"
    category: "top_performer"

  - id: "ultra_pearson_balanced_weights"
    name: "ULTRA: Pearson + Balanced Weights"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 1.8
      sad: 1.2
      anger: 1.2
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA Pearson with more balanced class weights"
    category: "top_performer"

  - id: "ultra_pearson_inverse_freq"
    name: "ULTRA: Pearson + Inverse Freq"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 0.8
      happy: 3.2
      sad: 1.8
      anger: 1.6
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA Pearson with inverse frequency class weights"
    category: "top_performer"

  - id: "ultra_pearson_all_optimized"
    name: "ULTRA: Pearson ALL Optimized"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 0.9
      happy: 2.2
      sad: 1.4
      anger: 1.4
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA Pearson with speaker + optimized class weights"
    category: "top_performer"

  # ========================================
  # TOP PERFORMER #2: BEST COMBO PEARSON (68.49% WA)
  # Testing speaker disentanglement and class weight variations
  # ========================================
  
  - id: "best_combo_pearson_original"
    name: "TOP4: Best Combo Pearson Original"
    learning_rate: 1e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.1
    description: "Original Best Combo Pearson (68.49% WA)"
    category: "top_performer"

  - id: "best_combo_pearson_no_speaker"
    name: "TOP4: Best Combo Pearson - Speaker"
    learning_rate: 1e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    use_speaker_disentanglement: false
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.1
    description: "Best Combo Pearson without speaker disentanglement"
    category: "top_performer"

  - id: "best_combo_pearson_soft_weights"
    name: "TOP4: Best Combo + Soft Weights"
    learning_rate: 1e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 2.0
      sad: 1.3
      anger: 1.3
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.1
    description: "Best Combo Pearson with softer class weights"
    category: "top_performer"

  - id: "best_combo_pearson_uniform_weights"
    name: "TOP4: Best Combo + Uniform"
    learning_rate: 1e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 1.0
      sad: 1.0
      anger: 1.0
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.1
    description: "Best Combo Pearson with uniform class weights"
    category: "top_performer"

  # ========================================
  # TOP PERFORMER #3: PLATEAU SCHEDULER (68.12% WA)
  # Testing speaker disentanglement and class weight variations
  # ========================================
  
  - id: "plateau_scheduler_original"
    name: "TOP3: Plateau Original"
    learning_rate: 3e-4
    weight_decay: 1e-4
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 512
      pooling: "max_mean"
      layer_norm: true
      dropout: 0.2
    description: "Original Plateau Scheduler (68.12% WA)"
    category: "top_performer"

  - id: "plateau_scheduler_speaker"
    name: "TOP3: Plateau + Speaker"
    learning_rate: 3e-4
    weight_decay: 1e-4
    use_speaker_disentanglement: true
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 512
      pooling: "max_mean"
      layer_norm: true
      dropout: 0.2
    description: "Plateau Scheduler + speaker disentanglement"
    category: "top_performer"

  - id: "plateau_scheduler_curriculum"
    name: "TOP3: Plateau + Curriculum"
    learning_rate: 3e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 3
      sad: 1.5
      anger: 1.5
    classifier_config:
      architecture: "simple"
      hidden_dim: 512
      pooling: "max_mean"
      layer_norm: true
      dropout: 0.2
    description: "Plateau Scheduler + curriculum learning"
    category: "top_performer"

  - id: "plateau_scheduler_all"
    name: "TOP3: Plateau ALL Features"
    learning_rate: 3e-4
    weight_decay: 1e-4
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 20
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 2.2
      sad: 1.4
      anger: 1.4
    classifier_config:
      architecture: "simple"
      hidden_dim: 512
      pooling: "max_mean"
      layer_norm: true
      dropout: 0.2
    description: "Plateau Scheduler with all features + optimized weights"
    category: "top_performer"

  # ========================================
  # NOVEL CLASS WEIGHTING STRATEGIES
  # Testing on best architecture (ULTRA Pearson)
  # ========================================
  
  - id: "ultra_focal_loss"
    name: "ULTRA: Focal Loss Strategy"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 1.5
      sad: 1.2
      anger: 1.2
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA with focal loss inspired class weights"
    category: "class_weighting"

  - id: "ultra_confusion_based"
    name: "ULTRA: Confusion-Based Weights"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 0.7  # Often over-predicted
      happy: 2.8    # Hardest to detect
      sad: 1.6      # Moderate confusion
      anger: 1.4    # Moderate confusion
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA with confusion matrix informed weights"
    category: "class_weighting"

  - id: "ultra_no_weights"
    name: "ULTRA: No Class Weights"
    learning_rate: 2e-4
    weight_decay: 5e-5
    use_curriculum_learning: true
    use_speaker_disentanglement: true
    difficulty_method: "pearson_correlation"
    curriculum_epochs: 15
    lr_scheduler: "plateau"
    class_weights:
      neutral: 1.0
      happy: 1.0
      sad: 1.0
      anger: 1.0
    classifier_config:
      architecture: "simple"
      hidden_dim: 1024
      pooling: "attention"
      layer_norm: true
      dropout: 0.05
    description: "ULTRA with no class weighting (uniform)"
    category: "class_weighting"

# Analysis settings
analysis:
  primary_metric: "iemocap_wa"
  secondary_metrics:
    - "iemocap_uar"
    - "cross_corpus_uar"
  
  research_questions:
    - "Does speaker disentanglement help the top performers?"
    - "Which class weighting strategy works best for 70%+ WA?"
    - "Can we break the 68.6% WA barrier with optimizations?"
    - "How do different pooling strategies affect top performance?"
    - "What is the optimal balance between curriculum and speaker features?"

# Expected runtime
estimated_runtime:
  total_experiments: 17
  minutes_per_experiment: 180  # ~3 hours per experiment (all sessions)
  total_hours: 51  # ~2+ days

# Expected improvements
expected_results:
  current_best: 0.6858  # ULTRA Pearson Maximum
  target_wa: 0.70       # Target 70% WA
  top_candidates:
    - "ultra_pearson_all_optimized"
    - "ultra_confusion_based"
    - "best_combo_pearson_soft_weights"
    - "plateau_scheduler_all"
    - "ultra_focal_loss"