# VAD Values Ablation Study
# Testing different expected VAD values for difficulty calculation

study_name: "vad_values_ablation"
wandb_project: "VAD_Difficulty_Ablation_shorter_MSP"

# Base config for all experiments
template_config: &template
  learning_rate: 9e-5
  weight_decay: 5e-6
  use_curriculum_learning: true
  use_speaker_disentanglement: false
  difficulty_method: "euclidean_distance"
  focal_loss: true
  focal_alpha: 0.25
  focal_gamma: 1.0
  label_smoothing: 0.1
  num_epochs: 30
  batch_size: 48
  class_weights:
    neutral: 0.8
    happy: 3.5
    sad: 1.8
    anger: 1.6

  # class_weights:
  #   neutral: 1
  #   happy: 1
  #   sad: 1
  #   anger: 1
  
  classifier_config:
    architecture: "simple"
    hidden_dim: 1536
    pooling: "attention"
    layer_norm: true
    dropout: 0.4
    input_dropout: 0.2
  curriculum_epochs: 10
  curriculum_pacing: "sqrt"
  use_difficulty_scaling: true
  training_direction: "MSP_to_IEMOCAP" #"IEMOCAP_to_MSP"

experiments:

  # ========== ORIGINAL/BASELINE VAD VALUES ==========
  
  - <<: *template
    id: "original_vad"
    name: "Curr+Scaling+Speaker"
    description: "Original expected VAD values from config"
    category: "baseline"
    expected_vad:
      0: [2.5, 2.5, 2.5]  # neutral
      1: [3.8, 3.2, 3.2]  # happy
      2: [1.8, 2.0, 2.0]  # sad 
      3: [2.0, 3.8, 3.5]  # anger

  - <<: *template
    id: "original_vad"
    name: "Curriculum Only"
    description: "Original expected VAD values from config"
    category: "baseline"
    expected_vad:
      0: [2.5, 2.5, 2.5]  # neutral
      1: [3.8, 3.2, 3.2]  # happy
      2: [1.8, 2.0, 2.0]  # sad 
      3: [2.0, 3.8, 3.5]  # anger
    use_speaker_disentanglement: false
    use_difficulty_scaling: false

  - <<: *template
    id: "original_vad"
    name: "Speaker_Only"
    description: "Original expected VAD values from config"
    category: "baseline"
    expected_vad:
      0: [2.5, 2.5, 2.5]  # neutral
      1: [3.8, 3.2, 3.2]  # happy
      2: [1.8, 2.0, 2.0]  # sad 
      3: [2.0, 3.8, 3.5]  # anger
    use_curriculum_learning: false
    use_difficulty_scaling: false
    use_speaker_disentanglement: true
        
  - <<: *template
    id: "baseline"
    name: "baseline_with_scaling"
    category: "basline"
    description: "Baseline without difficulty scaling or curriculum learning"
    expected_vad:
      0: [2.5, 2.5, 2.5]  # neutral
      1: [3.8, 3.2, 3.2]  # happy
      2: [1.8, 2.0, 2.0]  # sad 
      3: [2.0, 3.8, 3.5]  # anger
    use_curriculum_learning: false
    use_difficulty_scaling: true
    use_speaker_disentanglement: false

  - <<: *template
    id: "baseline"
    name: "baseline"
    category: "basline"
    description: "Baseline without difficulty scaling or curriculum learning"
    expected_vad:
      0: [2.5, 2.5, 2.5]  # neutral
      1: [3.8, 3.2, 3.2]  # happy
      2: [1.8, 2.0, 2.0]  # sad 
      3: [2.0, 3.8, 3.5]  # anger
    use_curriculum_learning: false
    use_difficulty_scaling: false
    use_speaker_disentanglement: false
  # # ========== CONSERVATIVE/CLOSER VALUES ==========
  
  # - <<: *template
  #   id: "conservative_vad"
  #   name: "Conservative VAD Values"
  #   description: "Less extreme VAD values, closer to neutral"
  #   category: "conservative"
  #   expected_vad:
  #     0: [3.0, 3.0, 3.0]  # neutral - middle
  #     1: [3.5, 3.3, 3.2]  # happy - mildly positive
  #     2: [2.3, 2.5, 2.7]  # sad - mildly negative
  #     3: [2.5, 3.5, 3.0]  # anger - neutral valence, higher arousal

  # # ========== LITERATURE-BASED VALUES ==========
  
  # - <<: *template
  #   id: "literature_vad"
  #   name: "Literature-Based VAD"
  #   description: "VAD values based on emotion literature studies"
  #   category: "literature"
  #   expected_vad:
  #     0: [3.0, 2.5, 3.0]  # neutral - calm, controlled
  #     1: [4.2, 3.5, 3.5]  # happy - high valence, moderate-high arousal
  #     2: [1.5, 2.0, 2.0]  # sad - low valence, low arousal, low dominance
  #     3: [2.2, 4.0, 3.2]  # anger - negative valence, very high arousal

  # # ========== AROUSAL-FOCUSED DIFFERENTIATION ==========
  
  # - <<: *template
  #   id: "arousal_focused_vad"
  #   name: "Arousal-Focused VAD"
  #   description: "Emphasize arousal differences between emotions"
  #   category: "arousal_focused"
  #   expected_vad:
  #     0: [3.0, 2.0, 3.0]  # neutral - low arousal
  #     1: [4.0, 3.8, 3.5]  # happy - high arousal
  #     2: [2.0, 1.5, 2.5]  # sad - very low arousal
  #     3: [2.5, 4.5, 3.0]  # anger - very high arousal

  # # ========== VALENCE-FOCUSED DIFFERENTIATION ==========
  
  # - <<: *template
  #   id: "valence_focused_vad"
  #   name: "Valence-Focused VAD"
  #   description: "Emphasize valence differences between emotions"
  #   category: "valence_focused"
  #   expected_vad:
  #     0: [3.0, 3.0, 3.0]  # neutral - middle valence
  #     1: [4.8, 3.2, 3.5]  # happy - very high valence
  #     2: [1.2, 2.5, 2.5]  # sad - very low valence
      # 3: [1.5, 3.8, 3.2]  # anger - low valence

analysis:
  primary_metric: "iemocap_wa"
  baseline_wa: 0.708
  
  research_questions:
    - "Which VAD value configuration produces the most meaningful difficulty scores?"
    - "Do extreme VAD values lead to better difficulty-accuracy correlations?"
    - "Should we focus on valence, arousal, or dominance differences?"
    - "How do different VAD approaches affect curriculum learning effectiveness?"

estimated_runtime:
  total_experiments: 6
  minutes_per_experiment: 240
  total_hours: 24